
def getlist():
    return {'cartwheel': 0,
            'catch': 1,
            'clap': 0,
            'climb': 0,
            'dive': 0,
            'draw_sword': 0,
            'dribble': 0,
            'fencing': 0,
            'flic_flac': 0,
            'golf': 0,
            'handstand': 0,
            'hit': 0,
            'jump': 0,
            'pick': 0,
            'pour': 0,
            'pullup': 0,
            'push': 0,
            'pushup': 0,
            'shoot_ball': 0,
            'sit': 0,
            'situp': 0,
            'swing_baseball': 0,
            'sword_exercise': 0,
            'throw': 0}
